### ISSUE TITLE
Create relaton-data-iana

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-iana#1]
Fill information from https://github.com/relaton/relaton-iana/issues/1

**Comment by ronaldtse** [comment]
Somehow this is failing: https://github.com/ietf-ribose/relaton-data-iana/runs/4330077128?check_suite_focus=true

**Comment by andrew2net** [comment]
@ronaldtse the issue is related to the [rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting). Authenticated users can make 5000 requests per hour, non authenticated only 60. The default GITHUB_TOKEN allows make up to 1000 requests per hour from GH actions.
I've tried to use the default GITHUB_TOKEN but unsuccessfully. The rate limit is sill 60 requests per hour.
Is it possible that the default permissions for GITHUB_TOKEN was changed?
